### ISSUE TITLE
Drupal 6 highly critical security release on March 28th (PSA-2018-001)

### ISSUE THREAD

**Issue by randysofia** [pressflow/6#114]
Are there plans to have this patch ready for Pressflow 6? @dsnopek https://www.mydropwizard.com/blog/drupal-6-highly-critical-security-release-march-28th-psa-2018-001

**Comment by dsnopek** [comment]
Yes! Please see https://www.drupal.org/project/d6lts/issues/2955130#comment-12544467

**Comment by mparker17** [comment]
Resolved in #116
