### ISSUE TITLE
Make @dsnopek a maintainer

### ISSUE THREAD

**Issue by mparker17** [pressflow/6#115]
# Problem / motivation

David Snopek (@dsnopek):

* maintains the [Drupal 6 Long Term Support project](https://www.drupal.org/project/d6lts) on Drupal.org,
* [is working on porting upcoming SA related to PSA-2018-001 to Drupal 6](https://www.drupal.org/project/d6lts/issues/2955130#comment-12539154), and,
* has contributed to a number of improvements to this repository already (#114, #112, #104, #101 (see comments)).

I no longer maintain any Drupal 6 sites, or work with it at all (and to some extent, started as a maintainer to pressflow/7).

It sounds to me like @dsnopek would make an excellent maintainer for pressflow/6!

# Proposed resolution

Add @dsnopek to the pressflow organization on Github.

**Comment by dsnopek** [comment]
Thanks @mparker17 :-)

**Comment by fluxsauce** [comment]
I have no objections, sounds like a good choice to me.

**Comment by pwolanin** [comment]
Yes, seems like a good idea.  I think we can trust him.

**Comment by joshkoenig** [comment]
+1

**Comment by joshkoenig** [comment]
@dsnopek you should have an invite. :)

**Comment by dsnopek** [comment]
Thanks, Everyone!
