### ISSUE TITLE
Missing tags for 6.45 and 6.46.

### ISSUE THREAD

**Issue by greg-1-anderson** [pressflow/6#124]
Could you please apply tags for the latest d6lts releases? Versions 6.45 and 6.46 exist on the master branch, but have not been tagged.

**Comment by greg-1-anderson** [comment]
A question on the tagging convention here.  Previous tags were https://github.com/pressflow/6/tree/pressflow-6.44.125, but the most recent release is https://github.com/pressflow/6/releases/tag/6.46.126 (without the "pressflow").

Are you planning on omitting the "pressflow" from tags henceforth? It doesn't matter too much to me, as long as it is consistent going forward. The pressflow/7 project also includes the word "pressflow-" in the tag names, fwiw.

**Comment by pwolanin** [comment]
oops - that was just me not paying attention

**Comment by pwolanin** [comment]
I think the tag is fixed now

**Comment by greg-1-anderson** [comment]
Thanks!
