### ISSUE TITLE
Cannot delete nodes, uninstall modules, or use any site-wide multi-step forms.

### ISSUE THREAD

**Issue by larryPlageman** [pressflow/6#70]
I am unable to use any aspect of my site with multi-step forms.

Deleting nodes from 'admin/content/node/' does not work, uninstalling (not disabling) modules does not work either.

Also, any modules providing multi step forms fail, in that once I reach the submit button for the form I am taken back to the beginning page of the form with a message that I did not select any options on that forms first page.

Any ideas would be most appreciated.

**Comment by pwolanin** [comment]
outdated?
